stages:
  - build
  - upload

variables:
  APP_VERSION: "v7.1.0.$CI_PIPELINE_IID"
  APPIMAGE_NAME: "PIP-OS-${APP_VERSION}-aarch64.AppImage"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/PIP-OS/${APP_VERSION}"

appimage-builder:
  stage: build
  image:
    name: "carlonluca/qt-dev:6.7.1"
    entrypoint: [""]
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - "assets/**/*"
        - "inc/**/*"
        - "qml/**/*"
        - "src/**/*"
        - "main.qml"
        - "main.cpp"
        - "AppImageBuilder.yml"
        - "CMakeLists.txt"
  cache:
    paths: [build/]
  before_script:
    - mkdir build
    - cd build
  script:
    - appimage-builder --recipe ../AppImageBuilder.yml
  artifacts:
    paths:
      - build/${APPIMAGE_NAME}

upload:
  stage: upload
  image: curlimages/curl:latest
  needs:
    - job: appimage-builder
      artifacts: true
  before_script:
    - ls -lh
  script:
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/${APPIMAGE_NAME} "${PACKAGE_REGISTRY_URL}/${APPIMAGE_NAME}"'

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
    - |
      release-cli create --name "Release ${APP_VERSION}" --tag-name ${APP_VERSION} \
        --assets-link "{\"name\":\"${APPIMAGE_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${APPIMAGE_NAME}\"}"
