stages:
  - build
  - upload

appimage-builder:
  stage: build
  image:
    name: "carlonluca/qt-dev:6.7.1"
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apt update
    - apt install libgpiod-dev
  script:
    - mkdir build
    - cd build
    - appimage-builder --recipe ../AppImageBuilder.yml
  artifacts:
    paths:
      - build/PIP-OS-latest-aarch64.AppImage

upload:
  stage: upload
  dependencies: [appimage-builder]
  script:
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/PIP-OS-latest-aarch64.AppImagee "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/PIP-OS/latest/PIP-OS-latest-aarch64.AppImage"'
