stages:
  - build
  - test
  - deploy

appimage-builder:
  stage: build
  image: carlonluca/qt-dev:6.7.1
  script:
    - mkdir build && cd build
    - appimage-builder --recipe ../AppImageBuilder.yml
  artifacts:
    paths:
      - build/PIP-OS-*.AppImage
