stages:
  - build
  - test
  - deploy

appimage-builder:
  stage: build
  image: 
    name: carlonluca/qt-dev:6.7.1
    entrypoint: [/bin/bash]
  script:
    - mkdir build && cd build
    - appimage-builder --recipe ../AppImageBuilder.yml
  artifacts:
    paths:
      - build/PIP-OS-*.AppImage
